# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}${{ matrix.config.static }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: '3.6', static: '-rwinlib'}
          - {os: windows-latest, r: '4.1', static: '-rwinlib'}
          - {os: windows-latest, r: 'next', static: '-rwinlib'}
          - {os: windows-latest, r: '4.1'}
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust on Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y cargo

      - name: Install Rust on Windows
        if: runner.os == 'Windows'
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: Add more rust targets
        if: runner.os == 'Windows'
        run: |
          rustup target add i686-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu

      - name: Use precompiled libgifski
        if: runner.os == 'Windows' && matrix.config.static
        run: Copy-Item src\Makevars.win.static src\Makevars.win

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
